# fly.toml app configuration file generated for kaiwa
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# Architecture:
# - Process "web": Main SvelteKit application (auto-scaled)
# - Cron jobs: Now handled by GitHub Actions with HTTP endpoints
#
# Note: Cron jobs have been migrated from Fly.io to GitHub Actions.
# The main app hosts HTTP endpoints that GitHub Actions calls on schedule.
# See .github/cron/README.md for documentation on the cron job setup.

app = 'kaiwa'
primary_region = 'den'

[build]

# Main web application process
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

# VM configuration for web process
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

