<script lang="ts">
	import { onMount } from 'svelte';
	import { trackPageView } from '$lib/analytics/posthog';
	import { SvelteDate } from 'svelte/reactivity';

	onMount(() => {
		trackPageView('/terms');
	});
</script>

<svelte:head>
	<title>Terms of Service - Kaiwa | Legal Agreement & User Rights</title>
	<meta
		name="description"
		content="Terms and conditions for using Kaiwa language learning platform. Understand your rights, responsibilities, and our service policies."
	/>
	<meta
		name="keywords"
		content="terms of service, user agreement, language learning, legal terms, subscription terms, user rights"
	/>
	<meta name="author" content="Kaiwa" />
	<meta name="robots" content="index, follow" />

	<!-- Open Graph / Facebook -->
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://trykaiwa.com/terms" />
	<meta property="og:title" content="Terms of Service - Kaiwa | Legal Agreement & User Rights" />
	<meta
		property="og:description"
		content="Terms and conditions for using Kaiwa language learning platform. Understand your rights, responsibilities, and our service policies."
	/>
	<meta property="og:site_name" content="Kaiwa" />

	<!-- Twitter -->
	<meta property="twitter:card" content="summary_large_image" />
	<meta property="twitter:url" content="https://trykaiwa.com/terms" />
	<meta
		property="twitter:title"
		content="Terms of Service - Kaiwa | Legal Agreement & User Rights"
	/>
	<meta
		property="twitter:description"
		content="Terms and conditions for using Kaiwa language learning platform. Understand your rights, responsibilities, and our service policies."
	/>

	<!-- Canonical URL -->
	<link rel="canonical" href="https://trykaiwa.com/terms" />

	<!-- Structured Data -->
	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "WebPage",
			"name": "Terms of Service - Kaiwa",
			"description": "Terms and conditions for using Kaiwa language learning platform",
			"url": "https://trykaiwa.com/terms",
			"publisher": {
				"@type": "Organization",
				"name": "Kaiwa",
				"url": "https://trykaiwa.com"
			},
			"dateModified": "2025-08-29"
		}
	</script>
</svelte:head>

<div class="container mx-auto max-w-3xl px-4 py-8 md:py-16">
	<header class="mb-12 border-b border-base-300 pb-8 text-center">
		<h1 class="text-3xl font-bold text-base-content md:text-4xl">Terms of Service</h1>
		<p class="mt-2 text-sm text-base-content/60">
			Last updated: {new SvelteDate().toLocaleDateString()}
		</p>
	</header>

	<div class="prose-base prose max-w-none">
		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				1. Acceptance of Terms
			</h2>
			<p class="text-base-content/80">
				By accessing and using Kaiwa ("the Service"), you accept and agree to be bound by the terms
				and provision of this agreement. If you do not agree to abide by the above, please do not
				use this service.
			</p>
		</section>

		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				2. Description of Service
			</h2>
			<p class="text-base-content/80">
				Kaiwa is an AI-powered language learning platform that provides conversational practice,
				personalized lessons, and progress tracking. The Service includes:
			</p>
			<ul class="list-disc pl-6 text-base-content/80">
				<li>AI-powered language conversations and tutoring</li>
				<li>Real-time voice and text interactions</li>
				<li>Personalized learning paths and progress tracking</li>
				<li>Grammar, vocabulary, and pronunciation feedback</li>
				<li>Learning scenario simulations and practice exercises</li>
			</ul>
		</section>

		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				3. AI Interaction Disclosure
			</h2>
			<p class="text-base-content/80">
				By using Kaiwa, you acknowledge and agree that you are primarily interacting with artificial
				intelligence (AI) systems, including but not limited to AI tutors, conversational agents,
				and automated language learning assistants. Unless explicitly stated otherwise or clearly
				indicated within the Service, all conversations, feedback, and educational content are
				generated by AI systems.
			</p>
			<h3 class="mt-6 text-lg font-semibold text-base-content">
				3.1 Data Sharing with AI Providers
			</h3>
			<p class="text-base-content/80">
				As detailed in our <a href="/privacy" class="link link-primary">Privacy Policy</a>,
				conversation data for free-tier users may be shared with our AI provider, OpenAI, to improve
				their services. Premium users benefit from stricter data privacy measures.
			</p>
		</section>

		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				4. User Accounts and Registration
			</h2>

			<h3 class="mt-6 text-lg font-semibold text-base-content">4.1 Account Creation</h3>
			<p class="text-base-content/80">
				To access certain features of the Service, you must create an account. You agree to provide
				accurate, current, and complete information during registration and to update such
				information to keep it accurate, current, and complete.
			</p>

			<h3 class="mt-6 text-lg font-semibold text-base-content">4.2 Account Security</h3>
			<p class="text-base-content/80">
				You are responsible for safeguarding the password and for all activities that occur under
				your account. You agree to notify us immediately of any unauthorized use of your account.
			</p>

			<h3 class="mt-6 text-lg font-semibold text-base-content">4.3 Age Requirements</h3>
			<p class="text-base-content/80">
				You must be at least 13 years old to use the Service. If you are under 18, you may only use
				the Service with the involvement of a parent or guardian.
			</p>
			<h4 class="mt-4 text-base font-medium text-base-content">4.3.1 Parental Responsibility</h4>
			<p class="text-base-content/80">
				Parents or guardians who allow their children under 18 to use the Service are responsible
				for their children's activity on the platform.
			</p>
		</section>

		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				5. Acceptable Use Policy
			</h2>

			<h3 class="mt-6 text-lg font-semibold text-base-content">5.1 Permitted Uses</h3>
			<p class="text-base-content/80">You may use the Service for:</p>
			<ul class="list-disc pl-6 text-base-content/80">
				<li>Personal language learning and practice</li>
				<li>Educational purposes in accordance with our guidelines</li>
				<li>Legitimate language acquisition and skill development</li>
			</ul>

			<h3 class="mt-6 text-lg font-semibold text-base-content">5.2 Prohibited Uses</h3>
			<p class="text-base-content/80">You may not use the Service to:</p>
			<ul class="list-disc pl-6 text-base-content/80">
				<li>Generate inappropriate, harmful, or offensive content</li>
				<li>Attempt to manipulate or abuse the AI system</li>
				<li>Violate any applicable laws or regulations</li>
				<li>Infringe on intellectual property rights</li>
				<li>Harass, abuse, or harm other users</li>
				<li>Attempt to gain unauthorized access to our systems</li>
			</ul>
		</section>

		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				6. Subscription Plans and Billing
			</h2>

			<h3 class="mt-6 text-lg font-semibold text-base-content">6.1 Free Tier</h3>
			<p class="text-base-content/80">
				We offer a free tier with limited features and usage quotas. Free tier users are subject to
				conversation limits and feature restrictions.
			</p>

			<h3 class="mt-6 text-lg font-semibold text-base-content">6.2 Premium Subscriptions</h3>
			<p class="text-base-content/80">
				Premium subscriptions provide additional features, higher usage limits, and priority
				support. Subscription fees are billed in advance on a monthly or annual basis.
			</p>

			<h3 class="mt-6 text-lg font-semibold text-base-content">
				6.3 Premium Features: 1-on-1 Calls with Founder
			</h3>
			<p class="text-base-content/80">
				Premium subscribers may receive monthly 1-on-1 calls with the founder as part of their
				subscription. This benefit is subject to the following conditions:
			</p>
			<ul class="list-disc pl-6 text-base-content/80">
				<li>Available while Premium subscriber base remains under 100 active members</li>
				<li>Calls are scheduled during designated office hours at mutually convenient times</li>
				<li>This benefit is guaranteed for up to 12 months from your subscription start date</li>
				<li>
					We reserve the right to modify this benefit with 30 days notice, which may include
					transitioning to alternative formats (such as extended office hours, priority email
					support, or other personalized guidance)
				</li>
				<li>
					Subscribers who joined while 1-on-1 calls were offered will receive equivalent value
					through alternative premium support if changes are made
				</li>
			</ul>

			<h3 class="mt-6 text-lg font-semibold text-base-content">6.4 Billing and Payment</h3>
			<ul class="list-disc pl-6 text-base-content/80">
				<li>All fees are non-refundable except as required by law</li>
				<li>Prices and features may change with 30 days notice</li>
				<li>Failed payments may result in service suspension</li>
				<li>Subscription renewals are automatic unless cancelled</li>
			</ul>

			<h3 class="mt-6 text-lg font-semibold text-base-content">6.5 Cancellation</h3>
			<p class="text-base-content/80">
				You may cancel your subscription at any time. Cancellation takes effect at the end of the
				current billing period. No refunds are provided for partial periods.
			</p>
		</section>

		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				7. Content and Intellectual Property
			</h2>

			<h3 class="mt-6 text-lg font-semibold text-base-content">7.1 User-Generated Content</h3>
			<p class="text-base-content/80">
				You retain ownership of content you create during conversations. However, you grant us a
				license to use this content to provide and improve the Service.
			</p>

			<h3 class="mt-6 text-lg font-semibold text-base-content">7.2 AI-Generated Content</h3>
			<p class="text-base-content/80">
				AI-generated responses and feedback are provided for educational purposes. We do not claim
				ownership of AI-generated content, but you may not claim it as your own work.
			</p>

			<h3 class="mt-6 text-lg font-semibold text-base-content">7.3 Service Content</h3>
			<p class="text-base-content/80">
				The Service, including its original content, features, and functionality, is owned by Kaiwa
				and is protected by international copyright, trademark, and other intellectual property
				laws.
			</p>
		</section>

		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				8. Privacy and Data Protection
			</h2>
			<p class="text-base-content/80">
				Your privacy is important to us. Our collection and use of personal information is governed
				by our Privacy Policy, which is incorporated into these Terms by reference.
			</p>
			<p class="text-base-content/80">
				By using the Service, you consent to the collection and use of information as outlined in
				our Privacy Policy, including the use of analytics tools like PostHog to improve user
				experience.
			</p>
		</section>

		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				9. Service Availability and Modifications
			</h2>

			<h3 class="mt-6 text-lg font-semibold text-base-content">9.1 Service Availability</h3>
			<p class="text-base-content/80">
				We strive to maintain high service availability but do not guarantee uninterrupted access.
				The Service may be temporarily unavailable due to maintenance, updates, or technical issues.
			</p>

			<h3 class="mt-6 text-lg font-semibold text-base-content">9.2 Service Modifications</h3>
			<p class="text-base-content/80">
				We reserve the right to modify, suspend, or discontinue the Service at any time. We will
				provide reasonable notice for significant changes that affect core functionality.
			</p>
		</section>

		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				10. Disclaimers and Limitations
			</h2>

			<h3 class="mt-6 text-lg font-semibold text-base-content">10.1 Educational Disclaimer</h3>
			<p class="text-base-content/80">
				While we strive to provide accurate language learning content, the Service is for
				educational purposes only. We do not guarantee fluency or proficiency in any language.
			</p>

			<h3 class="mt-6 text-lg font-semibold text-base-content">10.2 AI System Limitations</h3>
			<p class="text-base-content/80">
				AI systems may occasionally provide incorrect information or responses. Users should verify
				important information through other sources and use critical thinking when learning.
			</p>
			<h4 class="mt-4 text-base font-medium text-base-content">
				10.2.1 AI-Generated Content Disclaimer
			</h4>
			<p class="text-base-content/80">
				While we strive to make our AI safe, we are not responsible for any offensive,
				inappropriate, or harmful content it may generate. Users interact with the AI at their own
				risk.
			</p>

			<h3 class="mt-6 text-lg font-semibold text-base-content">10.3 Limitation of Liability</h3>
			<p class="text-base-content/80">
				To the maximum extent permitted by law, Kaiwa shall not be liable for any indirect,
				incidental, special, consequential, or punitive damages resulting from your use of the
				Service.
			</p>
		</section>

		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				11. Termination
			</h2>

			<h3 class="mt-6 text-lg font-semibold text-base-content">11.1 Termination by User</h3>
			<p class="text-base-content/80">
				You may terminate your account at any time by contacting our support team. Upon termination,
				your access to the Service will cease immediately.
			</p>

			<h3 class="mt-6 text-lg font-semibold text-base-content">11.2 Termination by Kaiwa</h3>
			<p class="text-base-content/80">
				We may terminate or suspend your account immediately, without prior notice, for conduct that
				we believe violates these Terms or is harmful to other users or the Service.
			</p>

			<h3 class="mt-6 text-lg font-semibold text-base-content">11.3 Effect of Termination</h3>
			<p class="text-base-content/80">
				Upon termination, your right to use the Service ceases immediately. We may delete your
				account and data in accordance with our data retention policies.
			</p>
		</section>

		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				12. Governing Law and Disputes
			</h2>

			<h3 class="mt-6 text-lg font-semibold text-base-content">12.1 Governing Law</h3>
			<p class="text-base-content/80">
				These Terms shall be governed by and construed in accordance with the laws of the
				jurisdiction where Kaiwa operates, without regard to conflict of law principles.
			</p>

			<h3 class="mt-6 text-lg font-semibold text-base-content">12.2 Dispute Resolution</h3>
			<p class="text-base-content/80">
				Any disputes arising from these Terms or your use of the Service shall be resolved through
				binding arbitration in accordance with the rules of the relevant arbitration association.
			</p>
		</section>

		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				13. Changes to Terms
			</h2>
			<p class="text-base-content/80">
				We reserve the right to modify these Terms at any time. We will notify users of material
				changes via email or through the Service. Continued use of the Service after changes
				constitutes acceptance of the new Terms.
			</p>
		</section>

		<section class="mb-10">
			<h2 class="border-l-4 border-primary pl-4 text-2xl font-semibold text-base-content">
				14. Contact Information
			</h2>
			<p class="text-base-content/80">
				If you have any questions about these Terms of Service, please contact us:
			</p>
			<ul class="list-disc pl-6 text-base-content/80">
				<li><strong class="font-semibold text-base-content">Legal</strong>: legal@trykaiwa.com</li>
				<li>
					<strong class="font-semibold text-base-content">Support</strong>: support@trykaiwa.com
				</li>
				<li>
					<strong class="font-semibold text-base-content">General</strong>: hello@trykaiwa.com
				</li>
			</ul>
		</section>
	</div>
</div>
