name: Send Weekly Practice Stats

on:
  schedule:
    # Weekly stats on Monday at 11:00 AM UTC
    - cron: '0 11 * * 1'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  send-weekly-stats:
    name: Send Weekly Practice Stats
    runs-on: ubuntu-latest
    steps:
      - name: Trigger weekly stats endpoint
        run: |
          response=$(curl -s -w "\n%{http_code}" "https://trykaiwa.com/api/cron/weekly-stats?secret=${{ secrets.CRON_SECRET }}")
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "Response: $body"

          if [ "$http_code" -ne 200 ]; then
            echo "Error: HTTP $http_code"
            exit 1
          fi
